### ISSUE TITLE
Any plans to update to Swift 3.0 ?

### ISSUE THREAD

**Issue by riklowe** [ooper-shlab/KMLViewer-Swift#1]
Would be good to see this project updated to Swift 3.0

**Comment by ooper-shlab** [comment]
OK, I'll put this project at the top of my "adapt to Swift 3.0" queue.

**Comment by ooper-shlab** [comment]
Done, please try.

**Comment by riklowe** [comment]
Perfect. Great job. Thanks

**Comment by bfandry** [comment]
Not sure whats going on as I haven't dug into it much but the subtitles aren't loading. Any clue on what is causing this?

EDIT: Scratch that noticed it wasn't being added to the point at line: 665. Any idea how to to get it to load the enriched html markup like mentioned in the example file? Or maybe change the pin icon based on the style icon?

**Comment by ooper-shlab** [comment]
The comments are left there as the original Apple's sample code. Maybe Apple's sample code programmer has left it for you to explore by yourself. And I have no intention to make my code any more than Apple's. Please fork this repository (or in any other ways you like), and try anything you want on it.

**Comment by bfandry** [comment]
Gotcha! Thanks for the swift conversion.
